version: '3.8'

services:
  database:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopass
    volumes:
      - database-data:/data/db

volumes:
  database-data:
