apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres-pod
spec:
  containers:
    - name: postgres-container
      image: postgres:15.3
      resources:
        limits:
          memory: '128Mi'
          cpu: '500m'
      envFrom:
        - configMapRef:
            name: postgres-config
        - secretRef:
            name: postgres-secret
      ports:
        - containerPort: 5432
      volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-storage
      persistentVolumeClaim:
        claimName: postgres-pvc
