apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  DATABASE_URL: postgres://fiap_tech_challenge:fiap-tech-challenge@fiap-tech-challenge.cosk748dgy0v.us-west-2.rds.amazonaws.com:5432/fiap_tech_challenge_db

